# Generated by Django 5.1.6 on 2025-03-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_image_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetail',
        ),
    ]
