# Generated by Django 5.1.6 on 2025-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
