# Generated by Django 5.1.6 on 2025-03-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='contact_image'),
        ),
    ]
