# Generated by Django 5.1.6 on 2025-03-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_acc_trans', to=settings.AUTH_USER_MODEL)),
                ('to_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_acc_trans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ('-created_at',),
            },
        ),
    ]
