# Generated by Django 5.1.6 on 2025-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('can_publish_article', 'Can Publish Article'), ('can_edit_article', 'Can Edit Article')],
            },
        ),
    ]
