# Generated by Django 5.1.6 on 2025-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('badiiy', 'Badiiy'), ('ilmiy', 'Ilmiy')], default='badiiy', max_length=20),
        ),
    ]
