# Generated by Django 5.1.6 on 2025-02-27 16:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('all_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
